# Generated by Django 6.0.1 on 2026-02-11 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_remove_user_username"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "Пользователь", "verbose_name_plural": "Пользователи"},
        ),
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True, help_text="загрузите аватар", null=True, upload_to="avatars/", verbose_name="аватар"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="city",
            field=models.CharField(
                blank=True, help_text="введите город", max_length=50, null=True, verbose_name="город"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(help_text="введите почту", max_length=254, unique=True, verbose_name="почта"),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                blank=True, help_text="введите номер телефона", max_length=15, null=True, verbose_name="номер телефона"
            ),
        ),
    ]
