# Generated by Django 6.0.1 on 2026-02-15 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_options_alter_user_avatar_alter_user_city_and_more"),
        ("users", "0003_payments"),
    ]

    operations = []
