# Generated by Django 6.0.1 on 2026-02-16 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_subscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="payments",
            name="link_for_payment",
            field=models.URLField(blank=True, max_length=400, null=True, verbose_name="Ссылка для оплаты"),
        ),
        migrations.AddField(
            model_name="payments",
            name="session_id",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="ID сессии"),
        ),
    ]
