# Generated by Django 6.0.1 on 2026-02-16 20:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0002_course_owner_lesson_owner"),
        ("users", "0006_payments_link_for_payment_payments_session_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payments",
            name="paid_course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="paid_course",
                to="materials.course",
                verbose_name="оплаченный курс",
            ),
        ),
        migrations.AlterField(
            model_name="payments",
            name="paid_lesson",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="paid_lesson",
                to="materials.lesson",
                verbose_name="оплаченный урок",
            ),
        ),
        migrations.AlterField(
            model_name="payments",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="пользователь",
            ),
        ),
    ]
